import MusicCard from "../components/MusicCard";
import PageWraper from "../components/PageWraper";
import Scroller from "../components/Scroller";

function page() {
  return (
    <PageWraper>

      <Scroller title="Top" routeTo="">
          <MusicCard
         imageUrl="/yohana.jpg"
         musicUrl=""
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
           <MusicCard
         imageUrl="/yohana.jpg"
         musicUrl=""
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
           <MusicCard
         imageUrl="/yohana.jpg"
         musicUrl=""
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
           <MusicCard
         imageUrl="/yohana.jpg"
         musicUrl=""
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
           <MusicCard
         imageUrl="/yohana.jpg"
         musicUrl=""
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
           <MusicCard
         imageUrl="/yohana.jpg"
         musicUrl=""
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
         <MusicCard
         imageUrl="/yohana.jpg"
         musicUrl=""
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
           <MusicCard
         imageUrl="/yohana.jpg"
         musicUrl=""
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
           <MusicCard
         imageUrl="/yohana.jpg"
         musicUrl=""
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
           <MusicCard
         imageUrl="/yohana.jpg"
         musicUrl=""
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
           <MusicCard
         imageUrl="/yohana.jpg"
         musicUrl=""
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
           <MusicCard
         imageUrl="/yohana.jpg"
         musicUrl=""
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
         <MusicCard
         imageUrl="/yohana.jpg"
         musicUrl=""
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
           <MusicCard
         imageUrl="/yohana.jpg"
         musicUrl=""
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
           <MusicCard
         imageUrl="/yohana.jpg"
         musicUrl=""
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
           <MusicCard
         imageUrl="/yohana.jpg"
         musicUrl=""
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
           <MusicCard
         imageUrl="/yohana.jpg"
         musicUrl=""
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
           <MusicCard 
         imageUrl="/yohana.jpg"
         musicUrl=""
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
      </Scroller>
    </PageWraper>
  );
}

export default page;
