import { ScrollArea, ScrollBar } from "@/components/ui/scroll-area";
import MusicCard from "../components/MusicCard";
import PageWraper from "../components/PageWraper";
import Scroller from "../components/Scroller";

function page() {
  return (
    <PageWraper>
      {
      // temporary route 
      }
      <Scroller title="Top" routeTo="">
          <MusicCard
          url="/yohana.jpg"
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
           <MusicCard
          url="/yohana.jpg"
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
           <MusicCard
          url="/yohana.jpg"
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
           <MusicCard
          url="/yohana.jpg"
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
           <MusicCard
          url="/yohana.jpg"
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
           <MusicCard
          url="/yohana.jpg"
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
         <MusicCard
          url="/yohana.jpg"
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
           <MusicCard
          url="/yohana.jpg"
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
           <MusicCard
          url="/yohana.jpg"
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
           <MusicCard
          url="/yohana.jpg"
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
           <MusicCard
          url="/yohana.jpg"
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
           <MusicCard
          url="/yohana.jpg"
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
         <MusicCard
          url="/yohana.jpg"
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
           <MusicCard
          url="/yohana.jpg"
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
           <MusicCard
          url="/yohana.jpg"
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
           <MusicCard
          url="/yohana.jpg"
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
           <MusicCard
          url="/yohana.jpg"
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
           <MusicCard 
          url="/yohana.jpg"
          alt="yohana"
          title="Yetalesh"
          artist="Yohana"
        />
      </Scroller>
    </PageWraper>
  );
}

export default page;
